name: "LambdaTest Cypress action"
description: "Integrate Cypress tests with LambdaTest."
author: "DawsonCodes"

inputs:
  LT_USERNAME:
    description: "LambdaTest username."
    required: true
  LT_ACCESS_KEY:
    description: "LambdaTest access key."
    required: true
  include_deps:
    description: "Moves dependencies and dev dependencies from your package.json file to the lambdatest-config.json file."
    default: false
  base_path:
    description: "The directory where the lambdatest-config.json file is located."
  cypress_config_file:
    description: "Path to the cypress config file."
  lambdatest_config_file:
    description: "Path to the lambdatest-config.json file."
  specs:
    description: "Path of a spec file, directory or a pattern to run."
  environment:
    description: "The environment to run the tests in."
  build_name:
    description: "The name of the LambdaTest build."
  tags:
    description: "The tags to be associated with the LambdaTest build."
  parallels:
    description: "The number of parallels to run the tests in."
  env_vars:
    description: "The environment variables to be set."
  tunnel:
    description: "The tunnel to be used."
  tunnel_name:
    description: "The name of the tunnel."
  browsers:
    description: "The browsers to run the tests in the format platform:browser:version."
  build_identifier:
    description: "The identifier of the build."
  ignore_files:
    description: "The files to be ignored."
  sync_mode:
    description: "The sync mode to be used."
  autostart:
    description: "Tunnel autostart."
  headless:
    description: "Run the tests in headless mode."
  network:
    description: "Capture network logs."
  exit_on_failure:
    description: "Exit with code 1 on failure."
  cypress_settings:
    description: "Pass in Cypress settings."
  geo_location:
    description: "The geo location to run the tests in."
  stop_on_failure:
    description: "Stop other tests if any test in session gets errored out."
  reject_unauthorized:
    description: "Default rejects self-signed SSL certificates in external requests."
  build_tags:
    description: "The tags to be associated with the LambdaTest build."
  system_env_variables:
    description: "System environment variables."
  env_file:
    description: "Path to a .env file."
  npm_force:
    description: "Force npm install."
  legacy_peer_deps:
    description: "Force npm install."
  vi_project:
    description: "Visual ui project name"
  vi_build:
    description: "Visual ui build name"
  vi_base:
    description: "Visual ui baseline"
  resolution:
    description: "Machine resolution"
  dedicated_proxy:
    description: "Dedicated proxy"
  npm_via_tunnel:
    description: "Install npm packages which are behind private VPN. Warning:This will increase the build duration of your tests."
  max_duration:
    description: "Maximum duration of the build."
  command_log:
    description: "Show command logs in the dashboard."
  retry_failed:
    description: "Retry failed tests in a new build."
  network_http2:
    description: "Capture HTTP2 network logs."
  network_ws:
    description: "Bypass web socket calls for network logs."
  network_sse:
    description: "Bypass SSE event calls for network logs."

runs:
  using: "node20"
  main: "dist/index.js"
